### PR TITLE
Fixing sonar issues

### LINKED ISSUE #377: SonarQube Issues
This issue tracks the remaining SonarQube findings across the codebase that affect maintainability, readability, consistency, and cognitive complexity. These issues are generally not causing major functional bugs, but they increase technical debt and make the code harder to understand and safely extend over time.

Some of the issues already identified include:

- removing redundant union types such as any | null and unknown | null
- merging duplicate imports from the same module
- removing unused imports and small dead-code leftovers
- marking component props as read-only where appropriate
- simplifying redundant conditions and avoiding unexpected negated conditions
- improving consistency in small helper methods and utility functions flagged by SonarQube
- replacing inline conditional expressions with precomputed variables
- extracting nested ternary operations into independent statements
- replacing repeated Platform.OS checks with reusable constants
- extracting repeated popup and floating UI logic into helper methods
- reducing JSX complexity by moving long inline arrays and conditional rendering into constants
- reducing cognitive complexity in large functions such as CampusMap and loadAllModes
- extracting repeated route rendering logic into reusable helper functions
- replacing verbose null checks with optional chaining where appropriate
- removing duplicate entries in regex character classes
- replacing older Node imports like fs, path, and readline with node:fs, node:path, and node:readline
- simplifying repeated route summary fallback values into reusable constants

The goal of this task is to review the current SonarQube warnings, group the low-, medium-, and high-severity findings, and apply safe refactoring changes without altering existing app behavior. All fixes should remain limited to code quality improvements only, with no accidental impact on navigation, indoor UI, Google Calendar integration, routing, marker rendering, or other working features.

Expected work:
	•	inspect current SonarQube findings in affected files
	•	fix maintainability, readability, and complexity issues one by one
	•	reduce cognitive complexity in large components and helper functions
	•	extract repeated logic into helper methods or reusable constants where appropriate
	•	simplify JSX by removing long inline conditionals and nested ternaries
	•	keep all existing functionality intact
	•	run tests after changes to confirm no regressions
	•	verify that map rendering, travel modes, route selection, indoor navigation, and calendar-related functionality still behave correctly
	•	prepare clean commits for each logical fix when possible

### PR DESCRIPTION
**Pull request by Akshey-Visu**
## Type of Change

- [ ] Feature
- [ ] Bug fix
- [ ] Refactor
- [X] SonarQube fix
- [ ] Documentation
- [ ] Other 

## Related Issue(s)

Closes #377 

## Scope of Changes

- Fixed all sonarqube issues
- Refactored high-complexity logic in CampusMap to reduce SonarQube cognitive complexity warnings

## Why This Change

This change was needed to reduce cognitive complexity warnings in CampusMap and related route rendering logic. The component had accumulated many inline conditions, nested ternaries, and branching UI logic, making it harder to read, maintain, and safely extend.

## Problem / Context

CampusMap contained multiple SonarQube findings related to excessive cognitive complexity. Several sections included repeated Platform checks, inline route mode arrays, nested popup state calculations, repeated summary fallback values, and large conditional rendering blocks.

While functionality was correct, the amount of inline branching made the component difficult to understand and increased the risk of introducing bugs during future changes.

## Implementation Notes

- Extracted popup and floating button calculations into a reusable getFloatingUiState helper
- Moved route origin and destination object generation into dedicated constants before useRouteNavigation
- Replaced repeated Platform.OS checks for pin tracking with shouldTrackStartPin and shouldTrackDestPin constants
- Extracted travel mode array generation into a reusable travelModes constant instead of building the array inline in JSX
- Replaced repeated activeSummary ternaries with arrivalTimeText, durationMinText, and distanceKmText constants
- Extracted selected route rendering and fitToCoordinates logic into applySelectedRouteRendering helper to reduce complexity inside loadAllModes
- Simplified JSX by replacing long conditional expressions with named variables

## How to Test

1. Pull this branch and install dependencies if needed
2. Run the test suite and confirm all tests still pass
3. Run SonarQube analysis or inspect the previously flagged files to verify that the addressed warnings are resolved

## Expected Result

-  The previously targeted SonarQube warnings should be reduced or removed
-  Existing app behavior should remain unchanged
- Tests should continue passing without regressions

## Types of Issues Fixed

- [X] Code smells
- [ ] Bugs
- [ ] Vulnerabilities
- [ ] Security hotspots
- [ ] Duplications
- [X] Maintainability issues
- [X] Reliability issues

## Technical Notes

- 

## Additional Notes

-

### CODE REVIEW

File: main/components/campus/CampusMap.tsx [hunk 1]
```diff
@@ -184,6 +184,108 @@ const GOOGLE_MODES: TravelMode[] = [
...
+  return {
+    hasBuildingPopup,
+    hasTravelPopup,
+    floatingBottom,
+    shouldShowCompass,
+    shouldHideFloatingButtons,
+  };
+}
+
+function applySelectedRouteRendering(params: {
```
Comment (Rami-66) [inline main/components/campus/CampusMap.tsx]: Same here you can extract applySelectRouteRendering and add it into main/hooks since this function manages Map state

File: main/components/campus/CampusMap.tsx [hunk 2]
```diff
@@ -184,6 +184,108 @@ const GOOGLE_MODES: TravelMode[] = [
   "bicycling",
 ];
 
+function getFloatingUiState(params: {
```
[the remark this answers is not in the document]
Comment (Akshey-Visu) [reply main/components/campus/CampusMap.tsx]: That does make sense, so I ended up getFloatingState in campusMap.ui.

File: main/components/campus/CampusMap.tsx (hunk 1 above)
Comment (Akshey-Visu) [reply main/components/campus/CampusMap.tsx]: I agree, however I thought it would be better to put it into a helper method, so I ended up putting it in a helper method called campusMap.routes instead. Let me know what you think about it and if you think putting it into hooks is still better
