### PR TITLE
bug/general bug fixes

### LINKED ISSUE #243: bug/bugfix-5 Icons cover Travel Pop Up
**Small UI bug we have flagged:**

As shown in the picture, both Get Directions icon and Current Location icon stay on TOP of the Travel Popup window when it is used making the interface look messy, and the overall user experience less pleasing (as it can get in the way and cover important information). 

**How it should work:**

The icons should remain BEHIND the pop up as it is the most logical order. Therefore the popup should appear in the foreground. 

**Note:**

The same issue is seen with the Building pop up window and must be fixed as well!

Image

### LINKED ISSUE #253: bug/bugfix-6 Map Orientation Not Reset After Exiting Navigation
### Description
After a user completes navigation and taps the Exit button, the map orientation does not automatically reset to the default north-facing direction.
The map remains rotated based on the last navigation heading, unless the user:

- Switches between SGW/Loyola campuses, or
- Taps the Current Location button

### Expected Behavior
When the user exits navigation:

- The map should automatically reset orientation to north
- The camera should remain centered in the same region

### Current Behavior

- Orientation remains rotated
- User has to manually click on the current location button or the toggle 

### Proposed Solution For Now
a) Automatically recenter and reset map when exiting navigation
b) Add a compass UI button allowing manual orientation reset

### LINKED ISSUE #276: bug/bugfix-9 Clear “X” Button can overflow outside navigation search bar for long location names
A very simple bug to fix :)

## Bug Description
When the start/destination name is long, the clear “X” button can shift and render partly outside the search bar in the navigation component, which breaks the layout (see the image below).

## Expected Behavior
The “X” button must always stay fully inside the search bar container (aligned to the right), regardless of the text length.

Image

### PR DESCRIPTION
**Pull request by fouadM200**
This pr contains 3 UI bug fixes reported from Sprint 4.

## Bugfix 5:
* Fixed the floating action buttons so the navigation, current location, and Google Calendar buttons now sit exactly on top of the collapsed popup window without any extra gap, keeping their alignment clean and consistent.
* Updated the popup interaction logic so when the building popup is expanded upward, all three floating buttons automatically disappear to prevent overlap and keep the popup content fully visible.

https://github.com/user-attachments/assets/64c0cbbd-a678-4670-805c-3b3775ed5dba

## Bugfix 6:
* Added a new ```Compass.tsx``` component to display a compass button on the map and let users quickly reset the map orientation.
* Added a new helper method in a dedicated ```mapCompass.ts``` file to handle resetting the map direction back to true north in a reusable way.
* Integrated the Compass component into ```CampusMap.tsx``` so it appears in the map UI and triggers the north-reset behavior correctly.
* Added unit tests to cover the new compass behavior and verify the helper logic and CampusMap integration work as expected.

https://github.com/user-attachments/assets/f1a293f2-4a7f-4781-a38b-f5b9c5728406

## Bugfix 9:
* Fixed the clear X button overflow by anchoring it inside the input container and reserving space on the right, so long location names no longer push it outside the search bar.

#### Additional fixes for prettier UI:
* Kept selected building labels visible from the beginning in the format code - full building name, instead of auto-scrolling to the cursor position.
* Added clean end truncation for long selected building names using ..., so the label stays readable without breaking the layout.

image

@Gibraltar-47 Can you review the code quality of all files edited?
@Akshey-Visu Can you review any refactoring suggestions?
@YashNathani0708 Can you review the final UI look and functionality of the fixed UI bugs?

Closes #276 
Closes #253 
Closes #243

### CODE REVIEW

File: main/components/campus/CampusMap.tsx [hunk 1]
```diff
@@ -750,11 +774,30 @@ export default function CampusMap() {
...
+  const collapsedBuildingPopupHeight = Math.round(windowHeight * 0.19);
+  const collapsedTravelPopupHeight = Math.max(
+    260,
+    Math.round(windowHeight * 0.28),
   );
 
+  const floatingBottom = useMemo(() => {
+    if (hasBuildingPopup) return collapsedBuildingPopupHeight;
+    if (hasTravelPopup) return collapsedTravelPopupHeight;
+    return 120;
```
Comment (Gibraltar-47) [inline main/components/campus/CampusMap.tsx]: *Problem*
useMemo() isn't necessarly useful and can be replaced for less complicated code while losing almost no performance.

*Fix*
replace the code with the following:

> const floatingBottom = hasBuildingPopup
>   ? collapsedBuildingPopupHeight
>   : hasTravelPopup
>     ? collapsedTravelPopupHeight
>     : 120;

*Advantage*
The code is simpler, easier to read and there is less memoization overhead.

File: main/components/campus/CampusMap.tsx [hunk 2]
```diff
@@ -750,11 +774,30 @@ export default function CampusMap() {
...
+  }, [
+    hasBuildingPopup,
+    hasTravelPopup,
+    collapsedBuildingPopupHeight,
+    collapsedTravelPopupHeight,
+  ]);
+
+  const shouldHideFloatingButtons =
+    (hasBuildingPopup && popupIndex > 0) || (hasTravelPopup && popupIndex > 0);
```
Comment (Gibraltar-47) [inline main/components/campus/CampusMap.tsx]: *Problem*
Code duplication with popupIndex > 0.

*Fix*
Replace it with the following code:

>const shouldHideFloatingButtons =
>    popupIndex > 0  || (hasTravelPopup && hasBuildingPopup);

*Advantage*
No more duplication (better code quality).

File: main/components/campus/CampusMap.tsx [hunk 3]
```diff
@@ -1234,6 +1309,18 @@ export default function CampusMap() {
           routeNavigation.exitNavigation();
           setAllRouteCoords([]);
           setShuttleSegmentCoords(null);
+
+          resetCompassToNorth(
```
Comment (Gibraltar-47) [inline main/components/campus/CampusMap.tsx]: Same for this:

>                resetCompassToNorth(resetCenter);

File: main/components/campus/CampusMap.tsx [hunk 4]
```diff
@@ -571,6 +594,7 @@ export default function CampusMap() {
 
     const target = routeNavigation.currentStep?.end;
     const heading = target ? bearingDegrees(userLocation, target) : 0;
```
[the remark this answers is not in the document]
Comment (fouadM200) [reply main/components/campus/CampusMap.tsx]: I agree with your Idea. This could be refactoring of extract method type! I'll definitely apply it.

File: main/components/campus/CampusMap.tsx (hunk 1 above)
Comment (fouadM200) [reply main/components/campus/CampusMap.tsx]: I agree. However, if I apply this change, I’ll get a new medium-level SonarQube issue, which may flag the nested ternary expression as reducing code readability and maintainability. Our goal is always reducing SonarQube issues in our project as much as we can.

You can clearly see the alert that I got when I used SonarQube extension in Webstorm IDE in the following screenshot.

image

I decided to write the same logic in a better alternative, while still keeping code simplicity and functionality:
```
    let floatingBottom = 120;

    if (hasBuildingPopup) {
        floatingBottom = collapsedBuildingPopupHeight;
    } else if (hasTravelPopup) {
        floatingBottom = collapsedTravelPopupHeight;
    }
```

File: main/components/campus/CampusMap.tsx (hunk 2 above)
Comment (fouadM200) [reply main/components/campus/CampusMap.tsx]: I agree! This could be a good refactoring of type "Consolidating conditional expression"

File: main/components/campus/CampusMap.tsx [hunk 5]
```diff
@@ -1102,46 +1143,77 @@ export default function CampusMap() {
...
+                  setStartText("");
+                  setDestText("");
+                  setQuery("");
+                  setAllRouteCoords([]);
+                  setShuttleSegmentCoords(null);
+
+                  resetCompassToNorth({
+                    latitude: region.latitude,
+                    longitude: region.longitude,
+                  });
```
[the remark this answers is not in the document]
Comment (fouadM200) [reply main/components/campus/CampusMap.tsx]: Done!!
